name: school_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  table_calendar: ^3.1.2

  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  socket_io_client: ^3.0.0
  image_picker: ^1.0.4
  file_picker: ^10.3.10
  dio: ^5.4.1
  path_provider: ^2.1.2
  url_launcher: ^6.3.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
